---
# Task: Fetch sosreport diagnostics

- name: Fetch sosreport archive md5
  fetch:
    src: "{{ tmpdir }}/{{ diag_filename }}.md5"
    dest: "{{ diag_path }}/{{ ansible_hostname }}/"
    fail_on_missing: yes
    flat: yes
    validate_checksum: yes

- name: Fetch sosreport archive
  fetch:
    src: "{{ tmpdir }}/{{ diag_filename }}"
    dest: "{{ diag_path }}/{{ ansible_hostname }}/"
    fail_on_missing: yes
    flat: yes
    validate_checksum: no
