---
# Task: Untar sosreport diagnostics

- name: Locally untar the sosreport archives
  local_action: shell tar xJf {{ diag_path}}/{{ ansible_hostname }}/{{ diag_filename}} -C {{ diag_path}}/{{ ansible_hostname }} --strip-components=1

- name: Make all local files writable (otherwise they cannot later be deleted)
  local_action: file mode="o+w" path="{{ diag_path}}/{{ ansible_hostname }}" recurse=yes
  ignore_errors: yes

- name: Remove the sosreport archive, which has now been untared
  local_action: command rm -f {{ diag_path}}/{{ ansible_hostname }}/{{ diag_filename}}

- name: Remove the sosreport archive checksum, which has now been untared
  local_action: command rm -f {{ diag_path}}/{{ ansible_hostname }}/{{ diag_filename}}.md5
